In [ ]:
Q1. What is the mathematical formula for a linear SVM?

Q2. What is the objective function of a linear SVM?

Q3. What is the kernel trick in SVM?

Q4. What is the role of support vectors in SVM Explain with example 

Q5. Illustrate with examples and graphs of Hyperplane, Marginal plane, Soft margin and Hard margin in
SVM?

Q6. SVM Implementation through Iris dataset.
Bonus task: Implement a linear SVM classifier from scratch using Python and compare its
performance with the scikit-learn implementation.

In [ ]:
Q1. What is the mathematical formula for a linear SVM?


A linear Support Vector Machine (SVM) for classification aims to find a hyperplane that best separates the classes of data points. The mathematical formula for a linear SVM can be described as follows:

Given a set of training data points (x₁, y₁), (x₂, y₂), ..., (xₙ, yₙ), where xᵢ is a feature vector and yᵢ is the corresponding class label (either -1 or +1), the linear SVM seeks to find the hyperplane represented by the equation:

w ⋅ x + b = 0

Here:

w is the weight vector perpendicular to the hyperplane.
x is the input feature vector.
b is the bias term.
The decision function can be expressed as:
f(x) = w ⋅ x + b

The prediction for a new data point x_new involves evaluating the sign of the decision function:

If f(x_new) ≥ 0, predict the positive class.
If f(x_new) < 0, predict the negative class.

Q2. What is the objective function of a linear SVM?


The objective function of a linear Support Vector Machine (SVM) is to find the optimal hyperplane that maximizes the margin between different classes of data points while minimizing classification errors. This is typically achieved by formulating a convex optimization problem

Q3. What is the kernel trick in SVM?

In a linear SVM, the decision boundary is a hyperplane that separates different classes. However, many real-world datasets are not linearly separable in their original feature space. The kernel trick addresses this limitation by introducing a mapping function (kernel function) that implicitly computes the dot product of the transformed feature vectors in a higher-dimensional space without actually computing the transformation itself.

Q4. What is the role of support vectors in SVM Explain with example 

Support vectors play a crucial role in Support Vector Machines (SVMs). They are the data points that are closest to the decision boundary (hyperplane) and have the most influence on determining the position and orientation of the decision boundary. These data points "support" the construction of the optimal hyperplane by helping to maximize the margin between classes. In essence, they are the critical elements that define the SVM's classification model.

Q5. Illustrate with examples and graphs of Hyperplane, Marginal plane, Soft margin and Hard margin in
SVM?

Let's consider a simple two-dimensional example with two classes: positive (+) and negative (-).

Hyperplane:
The hyperplane is the decision boundary that separates the two classes. In a 2D space, it's a line. The goal of an SVM is to find the hyperplane that maximizes the margin between the classes.

 
In this case, the solid line represents the hyperplane that separates the two classes.

Marginal Plane:
The marginal plane refers to the two parallel lines that run parallel to the hyperplane and are equidistant from it. The distance between the hyperplane and the marginal plane is the margin, and the support vectors lie on or between these planes.

The dashed lines represent the marginal planes, and the support vectors are the points touching or in-between these planes.

Hard Margin:
In a hard-margin SVM, the goal is to find a hyperplane that completely separates the classes without allowing any misclassification. This is suitable when the data is well-separated and noise-free. Hard-margin SVMs are sensitive to outliers.

The solid line is the hard-margin hyperplane, perfectly separating the classes.

Soft Margin:
In a soft-margin SVM, a margin of error is allowed, allowing some data points to be misclassified to achieve a better overall margin. This makes the SVM more robust to noisy data and outliers.


In this case, the dashed line represents the soft-margin hyperplane. Some data points are allowed to cross the marginal plane to accommodate the presence of noise or outliers.

Remember that the choice between hard and soft margins depends on the nature of the data. Hard-margin SVMs are suitable for well-separated, noise-free data, while soft-margin SVMs are more appropriate for data with noise or overlapping classes.



In [ ]:
Q6. SVM Implementation through Iris dataset.
Bonus task: Implement a linear SVM classifier from scratch using Python and compare its
performance with the scikit-learn implementation.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn import datasets

In [5]:
dataset = datasets.load_iris()

In [6]:
df = dataset.data

In [8]:
x = df

In [9]:
y = dataset.target

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=10)

In [12]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [13]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')

In [14]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [15]:
y_pred = svc.predict(x_test)

In [16]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[11  0  0]
 [ 0 15  0]
 [ 0  0 12]]
1.0


In [17]:
from sklearn.model_selection import GridSearchCV
 
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':['linear']
              }

In [18]:
grid=GridSearchCV(SVC(),param_grid=param_grid,refit=True,cv=5,verbose=3)

In [19]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.870 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.957 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.870 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.957 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.870 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear

[CV 2/5] END C=1000, gamma=0.001, kernel=linear;, score=0.913 total time=   0.0s
[CV 3/5] END C=1000, gamma=0.001, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END C=1000, gamma=0.001, kernel=linear;, score=0.955 total time=   0.0s
[CV 5/5] END C=1000, gamma=0.001, kernel=linear;, score=0.955 total time=   0.0s
[CV 1/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.957 total time=   0.0s
[CV 2/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.913 total time=   0.0s
[CV 3/5] END C=1000, gamma=0.0001, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.955 total time=   0.0s
[CV 5/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.955 total time=   0.0s


GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [20]:
grid.best_params_

{'C': 1, 'gamma': 1, 'kernel': 'linear'}

In [21]:
y_pred = grid.predict(x_test)

In [22]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[11  0  0]
 [ 0 15  0]
 [ 0  0 12]]
1.0
