In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [7]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [8]:
type(array_list)

numpy.ndarray

In [9]:
type(list_)

list

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
list_

['1', '2', '3', '4', '5']

In [3]:
list(map(lambda x:type(x),list_))

[str, str, str, str, str]

In [4]:
list(map(lambda x:type(x),array_list))

[numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_]

In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [5]:
array_list = np.array(object = list_, dtype = int)

In [6]:
array_list

array([1, 2, 3, 4, 5])

yes there is a difference in the data type

In [8]:
list(map(lambda x:type(x),list_))

[str, str, str, str, str]

In [9]:
list(map(lambda x:type(x),array_list))

[numpy.int32, numpy.int32, numpy.int32, numpy.int32, numpy.int32]

In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [10]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
num_array.shape

(2, 3)

In [13]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [15]:
arr = np.zeros((3,3))

In [16]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr.size

9

In [18]:
arr.shape

(3, 3)

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [22]:
arr2 = np.eye(5)

In [23]:
arr2


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr2.shape

(5, 5)